language: python
python: '3.6'

cache:
  - pip

env:
  global:
    - APP_SETTINGS=DevConfig
    - PIPENV_IGNORE_VIRTUALENVS=1
    - DESTINATION_IMAGE_NAME="$DOCKER_GCP_LOCATION/census-rm-ops"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv check
  - make test

after_success:
  - if ([ "$TRAVIS_BRANCH" == "rm-census" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || ([ "$TRAVIS_PULL_REQUEST_BRANCH" == "automate-census-docker-build" ]); then
    docker build -t "$DESTINATION_IMAGE_NAME" .;
    docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
    docker push "$DESTINATION_IMAGE_NAME";
    fi
  - pipenv run codecov

branches:
  only:
    - rm-census
