env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

container:
  port: 8080
service:
  port: 80

resources:
  requests:
    memory: "128Mi"

database:
  managedRedis: false

uaa:
  client_id: "test-ops-id"
  client_secret: "super-secret"